# ### STAGE 1: Build ###
FROM node:14-alpine AS build
WORKDIR /usr/src/app
COPY package.json package-lock.json ./
RUN npm install

COPY . .

# RUN chmod +x /public
# RUN chmod +x /temp

EXPOSE 8080

CMD [ "node", "server.js" ]

