version: '3'

services:
  app_backend:
    container_name: "infotec.ativo.backend"    
    build: ./backend
    command: ['./Server.Ativo']
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - ./log:/usr/src/app/log
    # environment:      
    #   MONGO_PORT: 27017
  app_frontend:
    container_name: "infotec.ativo.frontend"    
    build: ./frontend
    # command: ['node', 'server.js']
    restart: unless-stopped
    ports:
      - 8080:8080
    # volumes:
      # - ./log:/usr/src/app/log
    # environment:      
    #   MONGO_PORT: 27017       